on:
    push:
        branches-ignore:
            - 'master'
    pull_request:
        branches:
            - 'master'
jobs:
    test_and_package:
        runs-on: ubuntu-latest
        continue-on-error: false
        steps:
            - name: Checking out code base
              uses: actions/checkout@v2

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                java-version: 1.8

            - name: Testing and Packaging
              run: mvn clean test package -Dmaven.test.failure.ignore=false
              continue-on-error: false
